### ISSUE TITLE
hiveos problem

### ISSUE THREAD

**Issue by Macwill531** [tj8519/astrominer#12]
Hi, I have been working with this miner since yesterday that stoped completely, I updated but now is showing this error: astrominer no process found. Pool protocol is missing. I am using hiveos.

**Comment by tj8519** [comment]
you can ignore `astrominer no process found.`. hiveos just tried to kill old `astrominer` process if it exists.
`Pool protocol is missing.` means you missed `-p stratum` or `-p rpc` in the extra argument.
Please following this:
https://github.com/tj8519/astrominer/blob/main/running_on_hiveos.md
