### ISSUE TITLE
Custom Miner for HiveOS Created

### ISSUE THREAD

**Issue by jgonzis** [tj8519/astrominer#5]
Hi,

Helping the miners from Whalesburg I have added the Custom HiveOS Miner.

Miners can download it directly from this link, I hope it helps them:
https://github.com/jgonzis/astrominer/releases/download/v1.1.1/astrominer-1.1.1.HiveOS.tar.gz

I will try to be added also in Whalesburg.com repo

**Comment by Max3669** [comment]
![Sin título](https://user-images.githubusercontent.com/110992353/194732232-29ba39d4-9dec-406a-9b36-924c84964a26.png)
This, really, doesnt look good for an 10% fees.

**Comment by jgonzis** [comment]
> ![Sin título](https://user-images.githubusercontent.com/110992353/194732232-29ba39d4-9dec-406a-9b36-924c84964a26.png) This, really, doesnt look good for an 10% fees.

Totally right, not the first comment I saw...

**Comment by tj8519** [comment]
addressed
https://github.com/tj8519/astrominer/releases/tag/V1.3
