### ISSUE TITLE
HiveOS not showing stats v1.3

### ISSUE THREAD

**Issue by morti000** [tj8519/astrominer#6]
Hi

![image](https://user-images.githubusercontent.com/93385134/195094733-13dad787-7d85-476c-acfa-7d889843653b.png)

miss variable $khs in h-stats.sh

```
#!/usr/bin/env bash

. /hive/miners/custom/$CUSTOM_MINER/h-manifest.conf

stats=`nc -w 1 localhost 60666`
khs=$(echo $stats | cut -d ] -f 2 | cut -d [ -f 2)
```

![image](https://user-images.githubusercontent.com/93385134/195095117-a1351078-7be9-4704-b302-a80d25730cdd.png)

**Comment by tj8519** [comment]
thank you for the suggestion.
I have added this and a few more stas to the binary. now they can be fetched via `curl` or `nc` .
https://github.com/tj8519/astrominer/releases/download/V1.3/astrominer-v1.3_hiveosrev6.tar.gz
