### ISSUE TITLE
Can't start miner aarch64 

### ISSUE THREAD

**Issue by Saikatsaha1996** [tj8519/astrominer#7]
![Screenshot_2022-10-14-01-59-22-259_tech ula](https://user-images.githubusercontent.com/72664192/195704314-2ca4790a-bbfe-45a2-9318-39a3e53f3cdb.jpg)

**Comment by morti000** [comment]
same situation

![image](https://user-images.githubusercontent.com/93385134/195718115-21184d89-b10d-490a-a7ea-bab080c191ff.png)

**Comment by tj8519** [comment]
I'm working on this issue, expected to resolve it in a few days

**Comment by tj8519** [comment]
@Saikatsaha1996 @morti000 
the issue should be resolved on the latest aarch64 release
![image](https://user-images.githubusercontent.com/43113574/195966510-1bd692a9-8b38-4c14-acd8-19a21405f7f3.png)
https://github.com/tj8519/astrominer/releases/tag/V1.3
